Repository puppetlabs/puppet-editor-services, pull requests merged in 2020-04, with the labels that each got.

#239 (GH-238) Monkey patch Facter for minimal resets
  lib/puppet-languageserver-sidecar/facter_helper.rb
  lib/puppet-languageserver-sidecar/puppet_monkey_patches.rb
Labels: bug

#236 (maint) Update branding urls
  .github/issue_template.md
  .github/pull_request_template.md
  CHANGELOG.md
  lib/puppet-languageserver/document_store.rb
  tools/upload_release.ps1
Labels: maintenance

#243 GH 242 facts endpoint
  CHANGELOG.md
  lib/lsp/lsp_custom.rb
  lib/puppet-languageserver/message_handler.rb
  lib/puppet-languageserver/puppet_helper.rb
  lib/puppet-languageserver/sidecar_queue.rb
  lib/puppet_languageserver_sidecar.rb
  spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/facter_helper_spec.rb
Labels: enhancement

#244 (maint) Release 0.26.0
  CHANGELOG.md
  lib/puppet_editor_services/version.rb
Labels: maintenance
