Repository puppetlabs/puppet-editor-services, pull requests merged in 2020-03, with the labels that each got.

#226 (GH-221) Puppet Node Graph Response
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  lib/lsp/lsp_custom.rb
  lib/puppet-languageserver-sidecar/puppet_parser_helper.rb
  lib/puppet-languageserver-sidecar/sidecar_protocol_extensions.rb
  lib/puppet-languageserver/message_handler.rb
  lib/puppet-languageserver/sidecar_protocol.rb
  lib/puppet-languageserver/sidecar_queue.rb
  lib/puppet_languageserver_sidecar.rb
  spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb
  spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet-languageserver-sidecar_spec.rb
  spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet_helper_spec.rb
  spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet_parser_helper_spec.rb
  spec/languageserver-sidecar/unit/puppet-languageserver-sidecar/sidecar_protocol_extensions_spec.rb
  spec/languageserver/unit/puppet-languageserver/message_handler_spec.rb
  spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
Labels: enhancement

#225 (GH-207) Allow Qualified Resource Names in hover provider
  lib/puppet-languageserver/manifest/hover_provider.rb
  spec/languageserver/integration/puppet-languageserver/manifest/hover_provider_spec.rb
Labels: bug

#227 (maint) Release 0.25.0
  CHANGELOG.md
  lib/puppet_editor_services/version.rb
Labels: maintenance

#210 (GH-209) Refactor the session state to be a class and pass that instead of global modules
  lib/puppet-languageserver/client_session_state.rb
  lib/puppet-languageserver/crash_dump.rb
  lib/puppet-languageserver/document_store.rb
  lib/puppet-languageserver/facter_helper.rb
  lib/puppet-languageserver/global_queues.rb
  lib/puppet-languageserver/global_queues/sidecar_queue.rb
  lib/puppet-languageserver/global_queues/single_instance_queue.rb
  lib/puppet-languageserver/global_queues/validation_queue.rb
  lib/puppet-languageserver/language_client.rb
  lib/puppet-languageserver/manifest/completion_provider.rb
  lib/puppet-languageserver/manifest/definition_provider.rb
  lib/puppet-languageserver/manifest/hover_provider.rb
  lib/puppet-languageserver/manifest/signature_provider.rb
  lib/puppet-languageserver/manifest/validation_provider.rb
  lib/puppet-languageserver/message_handler.rb
  lib/puppet-languageserver/puppet_helper.rb
  lib/puppet-languageserver/session_state/document_store.rb
  lib/puppet-languageserver/session_state/language_client.rb
  lib/puppet-languageserver/session_state/object_cache.rb
  lib/puppet-languageserver/sidecar_protocol.rb
  lib/puppet-languageserver/sidecar_queue.rb
  lib/puppet-languageserver/uri_helper.rb
  lib/puppet-languageserver/validation_queue.rb
  lib/puppet_editor_services/server/tcp.rb
  lib/puppet_languageserver.rb
  spec/languageserver/fixtures/fact_object_cache.json
  spec/languageserver/fixtures/puppet_object_cache.json
  spec/languageserver/integration/puppet-languageserver/manifest/completion_provider_spec.rb
  spec/languageserver/integration/puppet-languageserver/manifest/definition_provider_spec.rb
  spec/languageserver/integration/puppet-languageserver/manifest/hover_provider_spec.rb
  spec/languageserver/integration/puppet-languageserver/manifest/signature_provider_spec.rb
  spec/languageserver/integration/puppet-languageserver/manifest/validation_provider_spec.rb
  spec/languageserver/integration/puppet-languageserver/session_state/document_store_spec.rb
  spec/languageserver/integration/puppet-languageserver/sidecar_queue_spec.rb
  spec/languageserver/spec_helper.rb
  spec/languageserver/unit/puppet-languageserver/client_session_state_spec.rb
  spec/languageserver/unit/puppet-languageserver/global_queues/sidecar_queue_spec.rb
  spec/languageserver/unit/puppet-languageserver/global_queues/single_instance_queue_spec.rb
  spec/languageserver/unit/puppet-languageserver/global_queues/validation_queue_spec.rb
  spec/languageserver/unit/puppet-languageserver/manifest/completion_provider_spec.rb
  spec/languageserver/unit/puppet-languageserver/manifest/document_symbol_provider_spec.rb
  spec/languageserver/unit/puppet-languageserver/message_handler_spec.rb
  spec/languageserver/unit/puppet-languageserver/puppet_helper_spec.rb
  spec/languageserver/unit/puppet-languageserver/session_state/document_store_spec.rb
  spec/languageserver/unit/puppet-languageserver/session_state/language_client_spec.rb
  spec/languageserver/unit/puppet-languageserver/session_state/object_cache_spec.rb
  spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
  spec/languageserver/unit/puppet-languageserver/validation_queue_spec.rb
  tools/generate_puppet_fixtures.rb
Labels: enhancement
